###======   Variables  ============
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjNjNjg2ODJjZDEzZDNlMTQ1NzBmYTI0IiwidXNlcm5hbWUiOiJuaW5hZDEyMyJ9LCJpYXQiOjE2NzUyNDY5MzIsImV4cCI6MTY3NTI4MjkzMn0.a3Aapwtm724hJBCd75SbIuaIKNNhSE8JAt2OJitVw48


###======   Testing  ============
###home api(for testing)
GET http://localhost:3100/api/name HTTP/1.1

###Post testing
POST http://localhost:3100/api/ytest HTTP/1.1
Content-Type: application/json

{
    "email": "test2@test.com"
}

###auth middleware testing
GET http://localhost:3100/api/auth/guard HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjNiNWFmNjE4MmE0NzYwYmYwY2UzNGRmIn0sImlhdCI6MTY3MjkwMzU3OCwiZXhwIjoxNjcyOTIxNTc4fQ.tvWRY84-35UF0mlZr0X8RFiLwiX-VrHKp9dslVCuO28

###======   Auth Routes  ============
###Register User
POST http://localhost:3100/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "fname": "jOey",
    "lname": "tibiaNi",
    "email": "test4@test.com",
    "username": "test4",
    "password": "testing"
}

###Login user
POST http://localhost:3100/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "ninad123",
    "password": "testing"

}

###verify user
GET http://localhost:3100/api/auth/verify HTTP/1.1
Authorization: {{authToken}}

###======   Profile Routes  ============
###Get user profile
GET http://localhost:3100/api/profile/ninad123?posts=true HTTP/1.1
Authorization: {{authToken}}


###Edit user profile
PUT http://localhost:3100/api/profile/edit HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "fname": "Test0",
    "lname": "Lname0",
    "email": "test12@test.com",
    "username":"test12",
    "password":"abc123",
    "bio": "test test tes",
    "dob": "test"
}

###Edit user profile
POST http://localhost:3100/api/profile/img HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "profileImg": "base64"
}

###======   Post Routes  ============
###Create new post
POST http://localhost:3100/api/post/new HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "text": "New post from test1"
}
###Get post by id
GET http://localhost:3100/api/post/63bd814b9ec882a0353670b2 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}


###======   Comment Routes  ============
###Create new comment
POST http://localhost:3100/api/comment HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "text": "New comment1",
    "postId": "63bd814b9ec882a0353670b2"
}

###Get comment by id
GET http://localhost:3100/api/comment/abc HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}
