###======   Testing  ============
###home api(for testing)
GET http://localhost:3100/api/name HTTP/1.1

###Post testing
POST http://localhost:3100/api/ytest HTTP/1.1
Content-Type: application/json

{
    "email": "test2@test.com"
}

###======   Auth Routes  ============
###Register User
POST http://localhost:3100/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "fname": "Test5",
    "lname": "Lname5",
    "email": "test7@test.com",
    "username": "test7",
    "password": "testing"
}

###Login user
POST http://localhost:3100/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "testing"

}
