###======   Variables  ============
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkYjg4ZWU5OWVhNDdmMDkwNGU2NmUwIiwidXNlcm5hbWUiOiJuaW5hZDEyMyIsIm5hbWUiOiJOaW5hZCBIYXRhbmthciJ9LCJpYXQiOjE2OTIxMDkyMzAsImV4cCI6MTY5MjE0NTIzMH0.JfrSB8b5TTbuy1jKUq4ZS1jB19Z2D5mKVdKat_zxTtw


###======   Testing  ============
###home api(for testing)
GET http://localhost:3100/api/name HTTP/1.1

###Post testing
POST http://localhost:3100/api/ytest HTTP/1.1
Content-Type: application/json

{
    "email": "test2@test.com"
}

###auth middleware testing
GET http://localhost:3100/api/auth/guard HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjNkYmU0ZWJjOTNmNGU3YjVlOThjYWI0IiwidXNlcm5hbWUiOiJuaW5hZDEyMyJ9LCJpYXQiOjE2ODkwNzE3ODEsImV4cCI6MTY4OTEwNzc4MX0.ICOwA5n112kBbjeaGup0aY-VhIDMS9vL1Vd8MJs1nfA

###======   Auth Routes  ============
###Register User
POST http://localhost:3100/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "fname": "jOey",
    "lname": "tibiaNi",
    "email": "test4@test.com",
    "username": "test4",
    "password": "testing"
}

###Login user
POST http://localhost:3100/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "ninad123",
    "password": "testing"

}

###verify user
GET http://localhost:3100/api/auth/verify HTTP/1.1
Authorization: {{authToken}}

###======   Profile Routes  ============
###Get user profile
GET http://localhost:3100/api/profile/ninad123?posts=true&followCount=true&select=fname,bio,profileImg HTTP/1.1
Authorization: {{authToken}}


###Edit user profile
PUT http://localhost:3100/api/profile/edit HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "fname": "Test0",
    "lname": "Lname0",
    "email": "test12@test.com",
    "username":"test12",
    "password":"abc123",
    "bio": "test test tes",
    "dob": "test"
}

###Edit user profile
POST http://localhost:3100/api/profile/img HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "profileImg": "base64"
}

###delete user profile
DELETE http://localhost:3100/api/profile HTTP/1.1
Authorization: {{authToken}}

###======   User Routes  ============
###get all users
# GET http://localhost:3100/api/user HTTP/1.1
# GET http://localhost:3100/api/user?select=fname,lname,following&omitUser=true HTTP/1.1
GET http://localhost:3100/api/user?select=fname,lname HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}


###Follow user
POST http://localhost:3100/api/user/follow HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "followingUserId": "64db88ff99ea47f0904e66e9"
}

###Unfollow user
POST http://localhost:3100/api/user/unfollow HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "unfollowingUserId": "64db890e99ea47f0904e66f2"
}



###======   Post Routes  ============
###Create new post
POST http://localhost:3100/api/post/new HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "text": "New post from test1"
}
###Get post by id
GET http://localhost:3100/api/post/63bd814b9ec882a0353670b2 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

### add like to post
GET http://localhost:3100/api/post/64b7fabf8db6d16a20d18563/like HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

### add unlike to post
GET http://localhost:3100/api/post/64b7fabf8db6d16a20d18563/unlike HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}


### get user's following post
GET http://localhost:3100/api/post/follow HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

### delete post
DELETE http://localhost:3100/api/post/64da3e0ceb96e9a9f2c5fc2f HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}



###======   Comment Routes  ============
###Create new comment
POST http://localhost:3100/api/comment HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "text": "New comment1",
    "postId": "64b7fabf8db6d16a20d18563"
}

###Get comments on post
GET http://localhost:3100/api/comment/post/64b7fabf8db6d16a20d18563 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}
